language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
sudo: required
services:
  - docker
before_intall:
  - docker pull osixia/openldap:1.2.0
  - docker run --name openldap -p 127.0.0.1:10389:389 -p 127.0.0.1:10636:636 --env LDAP_TLS_VERIFY_CLIENT=never --detach osixia/openldap:1.2.0 --loglevel debug
install:
  - python setup.py install
script:
  - nosetests
  - ./scripts/functional_test.py
  - docker logs openldap