language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
sudo: required
services:
  - docker
before_install:
  - docker pull ashafer01/openldap:1.3.0
  - docker pull jtgasper3/389ds-basic
  - docker run --name openldap -p 127.0.0.1:10389:389 -p 127.0.0.1:10636:636 --env LDAP_TLS_VERIFY_CLIENT=never --detach ashafer01/openldap:1.3.0 --loglevel debug
  - docker run --name 389ds -p 127.0.0.1:11389:389 --detach jtgasper3/389ds-basic
  - pip install -U pip
  - pip install setuptools
install:
  - ./scripts/build.sh --force
  - pip install ./dist/*.whl
script:
  - nosetests
  - ./scripts/integration_test.py
  - docker logs openldap
