"""Automatically generated by scripts/generate_extension_properties.py"""

from .extensible import ExtensionBase


class LDAPObjectExtensions(ExtensionBase):

    @property
    def descattrs(self):
        """
        :rtype: laurelin.extensions.descattrs.LaurelinLDAPObjectExtension
        """
        return self._get_extension_instance('descattrs')

    @property
    def netgroups(self):
        """
        :rtype: laurelin.extensions.netgroups.LaurelinLDAPObjectExtension
        """
        return self._get_extension_instance('netgroups')
